version: '3.8'
services:
  web:
    build: 
      context: .
      dockerfile: DockerfileL2E2
    container_name: web_container
    ports:
      - "5000:80"
    depends_on:
      - db
    volumes:
      - ./L2E2:/var/www/html
  db:
    build:
      context: .
      dockerfile: DockerfileL2E4
    container_name: db_container
