apiVersion: apps/v1
kind: Deployment
metadata:
  name: merged-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ODL6E3
  template:
    metadata:
      labels:
        app: ODL6E3
    spec:
      volumes:
      - name: web-files
        hostPath:
          path: /data/web
          type: DirectoryOrCreate
      containers:
      - name: odl2-web
        image: tjens23/odl2e2
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "localhost"
        volumeMounts:
        - name: web-files
          mountPath: /var/www/html
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: odl2-sql
        image: tjens23/odl2e4
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MYSQL_DATABASE
          value: "abook"
        ports:
        - containerPort: 3306
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: merged-service
spec:
  selector:
    app: ODL6E3
  ports:
    - name: web
      port: 80
      targetPort: 80
    - name: mysql
      port: 3306
      targetPort: 3306
  type: LoadBalancer
